// Types mirroring the Postgres schema, in the shape `supabase gen types typescript`
// produces — so this file can be regenerated over instead of hand-edited later:
//   npx supabase gen types typescript --project-id <ref> > src/live/database.types.ts

/** Values of the `public.activity_type` enum.
 *  TODO: confirm against the DB — `select unnest(enum_range(null::public.activity_type));`
 *  These mirror what src/live/mockData.tsx already declares. */
export const ActivityTypeEnum = {
  COMPETITION: "Competicion",
  TALK: "Charla",
  STAND: "Stand",
  WORKSHOP: "Taller",
  OTHER: "Otro"
} as const;

export type ActivityTypeEnum =
  (typeof ActivityTypeEnum)[keyof typeof ActivityTypeEnum];

/** Values of the `public.activity_status` enum. */
export const ActivityStatusEnum = {
  Pending: "PENDING",
  Confirmed: "CONFIRMED",
  Moved: "MOVED",
  Cancelled: "CANCELLED",
} as const;

export const ActivityLocationEnum = {
  MAKER_AT_DOMUS: "maker@domus",
  LABORATORIO: "Laboratorio",
  AUDITORIO: "Auditorio",
} as const;

export type ActivityStatusEnum =
  (typeof ActivityStatusEnum)[keyof typeof ActivityStatusEnum];

  export type ActivityLocationEnum =
  (typeof ActivityLocationEnum)[keyof typeof ActivityLocationEnum];

export type Database = {
  public: {
    Tables: {
      oshwdem_activity: {
        Row: {
          id: number;
          created_at: string;
          starts_at: string | null;
          ends_at: string | null;
          name: string | null;
          type: ActivityTypeEnum;
          max_people: number | null;
          sponsor: string | null;
          status: ActivityStatusEnum | null;
          location: ActivityLocationEnum;
          /** Optional: redundant now that MOVED is a status. Drop it if unused. */
          is_moved?: boolean | null;
        };
        // id is `generated by default as identity`, created_at defaults to now()
        Insert: {
          id?: number;
          created_at?: string;
          starts_at?: string | null;
          ends_at?: string | null;
          name?: string | null;
          type?: ActivityTypeEnum | null;
          max_people?: number | null;
          sponsor?: string | null;
          status?: ActivityStatusEnum | null;
          is_moved?: boolean | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          starts_at?: string | null;
          ends_at?: string | null;
          name?: string | null;
          type?: ActivityTypeEnum | null;
          max_people?: number | null;
          sponsor?: string | null;
          status?: ActivityStatusEnum | null;
          is_moved?: boolean | null;
        };
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: {
      activity_type: ActivityTypeEnum;
      activity_status: ActivityStatusEnum;
    };
    CompositeTypes: Record<never, never>;
  };
};

/** Convenience aliases. */
export type ActivityRow =
  Database["public"]["Tables"]["oshwdem_activity"]["Row"];
export type ActivityInsert =
  Database["public"]["Tables"]["oshwdem_activity"]["Insert"];
export type ActivityUpdate =
  Database["public"]["Tables"]["oshwdem_activity"]["Update"];
