// Types mirroring the Postgres schema, in the shape `supabase gen types typescript`
// produces — so this file can be regenerated over instead of hand-edited later:
//   npx supabase gen types typescript --project-id <ref> > src/live/database.types.ts

/** Values of the `public.activity_type` enum.
 *  TODO: confirm against the DB — `select unnest(enum_range(null::public.activity_type));`
 *  These mirror what src/live/mockData.tsx already declares. */
export const ActivityTypeEnum = {
  COMPETITION: "Competicion",
  TALK: "Charla",
  STAND: "Stand",
  EXPOSITION: "Exposicion",
  WORKSHOP: "Taller",
  OTHER: "Otro"
} as const;

export type ActivityTypeEnum =
  (typeof ActivityTypeEnum)[keyof typeof ActivityTypeEnum];

/** Values of the `public.activity_status` enum. */
export const ActivityStatusEnum = {
  Pending: "PENDING",
  Confirmed: "CONFIRMED",
  Moved: "MOVED",
  Cancelled: "CANCELLED",
} as const;

export const ActivityLocationEnum = {
  MAKER_AT_DOMUS: "maker@domus",
  LABORATORIO: "Laboratorio",
  AUDITORIO: "Auditorio",
} as const;

export type ActivityStatusEnum =
  (typeof ActivityStatusEnum)[keyof typeof ActivityStatusEnum];

  export type ActivityLocationEnum =
  (typeof ActivityLocationEnum)[keyof typeof ActivityLocationEnum];

/** Values of `oshwdem_maker.proposal_type`, as the call-for-makers form
 *  exports them. More WORKSHOP_* variants may exist on the form. */
export const MakerProposalTypeEnum = {
  STAND: "STAND",
  TALK: "TALK",
  WORKSHOP_EVERYONE: "WORKSHOP_EVERYONE",
} as const;

export type MakerProposalTypeEnum =
  (typeof MakerProposalTypeEnum)[keyof typeof MakerProposalTypeEnum];

/** Values of `oshwdem_maker.location`. Read as ActivityLocationEnum, so the
 *  page has one vocabulary for places. */
export const MakerLocationEnum = {
  LAB: "LAB",
  MAKER_AT_DOMUS: "MAKER_AT_DOMUS",
} as const;

export type MakerLocationEnum =
  (typeof MakerLocationEnum)[keyof typeof MakerLocationEnum];

export const MakerLevelEnum = {
  EVERYONE: "EVERYONE",
  BEGINNER: "BEGINNER",
  ADVANCED: "ADVANCED",
} as const;

export type MakerLevelEnum =
  (typeof MakerLevelEnum)[keyof typeof MakerLevelEnum];

export type Database = {
  public: {
    Tables: {
      oshwdem_activity: {
        Row: {
          id: number;
          created_at: string;
          starts_at: string | null;
          ends_at: string | null;
          /** Robot check-in opening time; only meaningful for competitions. */
          precheck_start: string | null;
          name: string | null;
          type: ActivityTypeEnum;
          max_people: number | null;
          sponsor: string | null;
          status: ActivityStatusEnum | null;
          location: ActivityLocationEnum;
          /** Optional: redundant now that MOVED is a status. Drop it if unused. */
          is_moved?: boolean | null;
        };
        // id is `generated by default as identity`, created_at defaults to now()
        Insert: {
          id?: number;
          created_at?: string;
          starts_at?: string | null;
          ends_at?: string | null;
          precheck_start?: string | null;
          name?: string | null;
          type?: ActivityTypeEnum | null;
          max_people?: number | null;
          sponsor?: string | null;
          status?: ActivityStatusEnum | null;
          is_moved?: boolean | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          starts_at?: string | null;
          ends_at?: string | null;
          precheck_start?: string | null;
          name?: string | null;
          type?: ActivityTypeEnum | null;
          max_people?: number | null;
          sponsor?: string | null;
          status?: ActivityStatusEnum | null;
          is_moved?: boolean | null;
        };
        Relationships: [];
      };
      /** One row per call-for-makers proposal. Mirrors the form's public export
       *  (makers_public_*.csv). */
      oshwdem_maker: {
        Row: {
          id: number;
          created_at: string;
          /** The form's own submission id, e.g. "lDMM6". */
          submission_id: string | null;
          proposal_type: MakerProposalTypeEnum;
          project_name: string;
          description: string | null;
          link_to_project: string | null;
          /** Sign-up form, for workshops with limited places. */
          inscription_link: string | null;
          logo: string | null;
          participant_names: string | null;
          /** Who the participants are with, shown after their names. */
          organization: string | null;
          sponsor_id: number | null;
          duration_minutes: number | null;
          start_time: string | null;
          end_time: string | null;
          location: MakerLocationEnum | null;
          /** Plain-language topics for visitors, e.g. {"Impresión 3D",IA}. */
          tags: string[] | null;
          /** Practical note for attendees, e.g. "Trae tu portátil". */
          notes: string | null;
          level: MakerLevelEnum | null;
          /** File name in src/live/backgrounds shown faded behind the card. */
          background: string | null;
        };
        // id is `generated by default as identity`, created_at defaults to now()
        Insert: {
          id?: number;
          created_at?: string;
          submission_id?: string | null;
          proposal_type: MakerProposalTypeEnum;
          project_name: string;
          description?: string | null;
          link_to_project?: string | null;
          inscription_link?: string | null;
          logo?: string | null;
          participant_names?: string | null;
          organization?: string | null;
          sponsor_id?: number | null;
          duration_minutes?: number | null;
          start_time?: string | null;
          end_time?: string | null;
          location?: MakerLocationEnum | null;
          tags?: string[] | null;
          notes?: string | null;
          level?: MakerLevelEnum | null;
          background?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          submission_id?: string | null;
          proposal_type?: MakerProposalTypeEnum;
          project_name?: string;
          description?: string | null;
          link_to_project?: string | null;
          inscription_link?: string | null;
          logo?: string | null;
          participant_names?: string | null;
          organization?: string | null;
          sponsor_id?: number | null;
          duration_minutes?: number | null;
          start_time?: string | null;
          end_time?: string | null;
          location?: MakerLocationEnum | null;
          tags?: string[] | null;
          notes?: string | null;
          level?: MakerLevelEnum | null;
          background?: string | null;
        };
        Relationships: [];
      };
      oshwdem_collaborator: {
        Row: {
          id: number;
          image_link: string | null;
          linked_webpage: string | null;
          order: number;
        };
        Insert: {
          id?: number;
          image_link?: string | null;
          linked_webpage?: string | null;
          order: number;
        };
        Update: {
          id?: number;
          image_link?: string | null;
          linked_webpage?: string | null;
          order?: number;
        };
        Relationships: [];
      };
    };
    Views: Record<never, never>;
    Functions: Record<never, never>;
    Enums: {
      activity_type: ActivityTypeEnum;
      activity_status: ActivityStatusEnum;
    };
    CompositeTypes: Record<never, never>;
  };
};

/** Convenience aliases. */
export type ActivityRow =
  Database["public"]["Tables"]["oshwdem_activity"]["Row"];
export type ActivityInsert =
  Database["public"]["Tables"]["oshwdem_activity"]["Insert"];
export type ActivityUpdate =
  Database["public"]["Tables"]["oshwdem_activity"]["Update"];
export type MakerRow =
  Database["public"]["Tables"]["oshwdem_maker"]["Row"];
export type CollaboratorRow =
  Database["public"]["Tables"]["oshwdem_collaborator"]["Row"];
